## 1.1 NumPy

NumPy (Numerical Python) is the foundational library for scientific computing in Python. It provides a high-performance multidimensional array object called ndarray and a large collection of mathematical functions to operate on these arrays efficiently.

- Python lists are slow for numerical work — they store pointers, not raw values 
- NumPy arrays store homogeneous, typed data in contiguous memory → much faster 
- Vectorised operations eliminate explicit Python loops
- Forms the backbone of Pandas, Matplotlib, Scikit-learn, TensorFlow, SciPy 
- Native support for linear algebra, Fourier transforms, and random sampling

## 1.2 Importing NumPy

In [13]:
import numpy as np
print(np.__version__)

2.1.3


## 1.3 Checking constants

In [9]:
print(np.pi) 
print(np.e)
print(np.inf)
print(np.nan)

3.141592653589793
2.718281828459045
inf
nan


## 2.1 Creating NumPy Arrays

In [10]:
a = np.array([10, 20, 30, 40])
print(a) 
print(type(a))

[10 20 30 40]
<class 'numpy.ndarray'>


In [11]:
m = np.array([[1, 2, 3],[4, 5, 6]])
print(m)
print(m.shape)
print(m.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [7]:
b = np.array([1, 2, 3], dtype=float)
print(b)
print(b.dtype)

[1. 2. 3.]
float64


In [8]:
c = np.array([1.5, 2.7], dtype=int)
print(c)
print(c.dtype)

[1 2]
int64


## 2.2 Factory Functions

Functions

In [24]:
a1 = np.zeros((3, 4))
print("Zeroes\n:",a1)
a2 = np.ones((2, 3))
print("\nOnes:\n",a2)
a3 = np.full((2, 2), 7)
print("\nFull:\n",a3)
a4 = np.eye(3) 
print("\nIdentity:\n",a4)
a5 = np.empty((2, 2))
print("\nEmpty:\n",a5)

Zeroes
: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full:
 [[7 7]
 [7 7]]

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Empty:
 [[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]


Range Based

In [31]:

print("Range:", np.arange(10))
print("Arange:", np.arange(0, 1, 0.2))
print("Linspace:", np.linspace(0, 1, 5))
print("Logspace:", np.logspace(0, 2, 3))


Range: [0 1 2 3 4 5 6 7 8 9]
Arange: [0.  0.2 0.4 0.6 0.8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Logspace: [  1.  10. 100.]


Random Array

In [28]:
print("\nRandom:\n", np.random.rand(3, 3))
print("\nStandard Normal:\n", np.random.randn(3, 3))
print("\nRandom Integers:\n", np.random.randint(1, 10, size=(3, 3)))


Random:
 [[0.97648684 0.42139592 0.12779073]
 [0.05147317 0.49291824 0.22681321]
 [0.34751831 0.81985696 0.37979834]]

Standard Normal:
 [[ 0.99296359  0.71652767  0.83038635]
 [-0.21544836 -0.03314223 -0.6492154 ]
 [-0.27704588  1.33937225  0.02992952]]

Random Integers:
 [[8 1 7]
 [5 5 2]
 [8 7 9]]


## 2.3 Tasks — Creating Arrays

Task 2.3.1: Create a 1D array of integers from 5 to 50 in steps of 5. Print its shape and dtype.

Task 2.3.2: Create a 4×4 matrix of zeros and then set the diagonal elements to 1 (without using np.eye). Hint: use indexing with range().

Task 2.3.3: Generate an array of 20 evenly-spaced values between 0 and 2π (np.pi). Compute sin of each value.

Task 2.3.4: Create a 3×3 random integer array with values between 10 and 99. Find its minimum and maximum values.

Task 2.3.5: Build a 5×5 checkerboard pattern (alternating 0s and 1s) using slicing and zeros.

In [42]:
print("Task 2.3.1\n")
arr = np.arange(5, 51, 5)
print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

Task 2.3.1

Array: [ 5 10 15 20 25 30 35 40 45 50]
Shape: (10,)
Data Type: int64


In [43]:
print("\nTask 2.3.2\n")
matrix = np.zeros((4, 4))
print("Matrix Before: \n", matrix)
for i in range(4):
    matrix[i, i] = 1    
print("\nMatrix After: \n",matrix)



Task 2.3.2

Matrix Before: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Matrix After: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
print("\nTask 2.3.3\n")
angles = np.linspace(0, 2 * np.pi, 20)
sines = np.sin(angles)
print("Angles:\n", angles)
print("\nSines:\n", sines)



Task 2.3.3

Angles:
 [0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]

Sines:
 [ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]


In [46]:
print("\nTask 2.3.4\n")
rand_int_array = np.random.randint(10, 100, size=(3, 3))
print("Random Integer Array:\n", rand_int_array)
print("Minimum Value:", np.min(rand_int_array))
print("Maximum Value:", np.max(rand_int_array))


Task 2.3.4

Random Integer Array:
 [[30 13 62]
 [26 78 11]
 [27 97 72]]
Minimum Value: 11
Maximum Value: 97


In [48]:
print("\nTask 2.3.5\n")
checkerboard = np.zeros((5, 5), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern:\n", checkerboard)



Task 2.3.5

Checkerboard Pattern:
 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


## 3.1 Array Attributes

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9,10,11,12]])
print("Shape:",a.shape) 
print("Number of dimensions:",a.ndim)

print("\nData type:",a.dtype)
print("Item size:",a.itemsize)
print("Total bytes:",a.nbytes)

b = a.astype(np.float32) 
print("\nData type:",b.dtype) 
print("Total bytes:",b.nbytes)
print("Transposed shape:",a.T.shape)

Shape: (3, 4)
Number of dimensions: 2

Data type: int64
Item size: 8
Total bytes: 96

Data type: float32
Total bytes: 48
Transposed shape: (4, 3)


## 3.2 Tasks — Attributes

Task 3.2.1: Create a (4, 3, 2) array of ones. Print its ndim, shape, size, and total memory in bytes.

Task 3.2.2: Create an int64 array and convert it to float32. Compare nbytes before and after.

Task 3.2.3: Write a function describe(arr) that prints all six attributes of any given array.

In [55]:
print("Task 3.2.1\n")
a = np.ones((4, 3, 2))
print("Number of dimensions:", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Total bytes:", a.nbytes)


Task 3.2.1

Number of dimensions: 3
Shape: (4, 3, 2)
Size: 24
Total bytes: 192


In [58]:
print("Task 3.2.2\n")
a = np.array([1, 2, 3], dtype=np.int64)
print("Original array:\n", a)
print("Original nbytes:", a.nbytes)
b = a.astype(np.float32)
print("\nConverted array:\n", b)
print("Converted nbytes:", b.nbytes)


Task 3.2.2

Original array:
 [1 2 3]
Original nbytes: 24

Converted array:
 [1. 2. 3.]
Converted nbytes: 12


In [60]:
print("Task 3.2.3\n")
def describe(arr):
    print("Shape:", arr.shape)
    print("Number of dimensions:", arr.ndim)
    print("Data type:", arr.dtype)
    print("Item size:", arr.itemsize)
    print("Total bytes:", arr.nbytes)
    print("Size:", arr.size)

arr = np.array([[1, 2], [3, 4]])
describe(arr)

Task 3.2.3

Shape: (2, 2)
Number of dimensions: 2
Data type: int64
Item size: 8
Total bytes: 32
Size: 4


## 4.1 Indexing & Slicing

In [61]:
a = np.array([10, 20, 30, 40, 50, 60])

print(a[0]) # 10
print(a[-1]) # 60
print(a[1:4]) # [20 30 40]
print(a[::2]) # [10 30 50]
print(a[::-1]) # [60 50 40 30 20 10]


10
60
[20 30 40]
[10 30 50]
[60 50 40 30 20 10]


In [65]:
s = a[2:5]
s[0] = 99

print(s)

[99 40 50]


In [67]:
c = a[2:5].copy()
c[0] = 0 
print(c)

[ 0 40 50]


## 4.2 2D Indexing

In [70]:
m = np.arange(1, 13).reshape(3, 4)
print(m)
print(m[0, 2]) # 3 (row 0, col 2)
print(m[1, :]) # [5 6 7 8] row 1
print(m[:, 2]) # [3 7 11] col 2
print(m[0:2, 1:3]) # [[2 3],[6 7]] sub-matrix
print(m[-1, -1]) # 12 last element
print(m[0:2, 1:3]) # [[2 3],[6 7]] sub-matrix


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
[5 6 7 8]
[ 3  7 11]
[[2 3]
 [6 7]]
12
[[2 3]
 [6 7]]


## 4.3 Tasks - Indexing

Task 4.3.1: Given arr = np.arange(1, 26).reshape(5, 5), extract the 3×3 sub-matrix from the centre.


Task 4.3.2: Reverse every row of a 4×4 random integer matrix using slicing.

Task 4.3.3: From the array [34, -5, 12, 0, -8, 99, 47, -1], extract all negative values and replace them with their absolute values in the original array.

Task 4.3.4: Create a 6×6 identity-like matrix using np.eye, then set all values in rows 2–4 and columns 2–4 to 5.

Task 4.3.5: Use np.where to classify an array of 10 random scores (0–100): 'A' if ≥ 80, 'B' if ≥ 60, else 'C'.

In [73]:
print("\nTask 4.3.1\n")
arr = np.arange(1, 26).reshape(5, 5)
center = arr[1:4, 1:4]

print("Original Matrix:")
print(arr)

print("\n3×3 Centre Sub-Matrix:")
print(center)


Task 4.3.1

Original Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

3×3 Centre Sub-Matrix:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [74]:
print("Task 4.3.2\n")
arr = np.random.randint(1, 100, (4, 4))

print("Original Matrix:")
print(arr)

reversed_rows = arr[:, ::-1]

print("\nRows Reversed:")
print(reversed_rows)

Task 4.3.2

Original Matrix:
[[95 37 73 95]
 [63 19 26 85]
 [87 94 72 81]
 [10 88 45  7]]

Rows Reversed:
[[95 73 37 95]
 [85 26 19 63]
 [81 72 94 87]
 [ 7 45 88 10]]


In [75]:
print("\nTask 4.3.3\n")

arr = np.array([34, -5, 12, 0, -8, 99, 47, -1])

print("Original Array:")
print(arr)

negatives = arr[arr < 0]

print("\nNegative Values:")
print(negatives)

arr[arr < 0] = np.abs(arr[arr < 0])

print("\nUpdated Array:")
print(arr)


Task 4.3.3

Original Array:
[34 -5 12  0 -8 99 47 -1]

Negative Values:
[-5 -8 -1]

Updated Array:
[34  5 12  0  8 99 47  1]


In [76]:
print("\nTask 4.3.4\n")
arr = np.eye(6)

print("Original Matrix:")
print(arr)

arr[1:4, 1:4] = 5

print("\nModified Matrix:")
print(arr)


Task 4.3.4

Original Matrix:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Modified Matrix:
[[1. 0. 0. 0. 0. 0.]
 [0. 5. 5. 5. 0. 0.]
 [0. 5. 5. 5. 0. 0.]
 [0. 5. 5. 5. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [78]:
print("Task 4.3.5\n")
scores = np.random.randint(0, 101, 10)

grades = np.where(scores >= 80, 'A',
         np.where(scores >= 60, 'B', 'C'))

print("Scores:")
print(scores)

print("\nGrades:")
print(grades)

Task 4.3.5

Scores:
[28 62 54 79 56 33 73 48 84 50]

Grades:
['C' 'B' 'C' 'B' 'C' 'C' 'B' 'C' 'A' 'C']


## 5 Array Operations & Universal Functions

## 5.1 Element-wise Arithmetic

In [80]:
a = np.array([1, 2, 3, 4]) 
b = np.array([10, 20, 30, 40])
print("Addition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)
print("Floor Division:", b // a)
print("Modulus:", b % 3)
print("Square:", a ** 2)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Floor Division: [10 10 10 10]
Modulus: [1 2 0 1]
Square: [ 1  4  9 16]


## 5.2 Universal Functions (ufuncs)

In [86]:
a = np.array([1, 4, 9, 16])

print("Square Root:", np.sqrt(a))
print("\nSquare:", np.square(a))
print("\nAbsolute Values:", np.abs(np.array([-1, -2, 3])))
print("\nExponential:", np.exp(np.array([0, 1, 2])))

print("\nNatural Logarithm:", np.log(a))
print("\nBase-2 Logarithm:", np.log2(a))
print("\nBase-10 Logarithm:", np.log10(a))

print("\nSine Values:", np.sin(np.linspace(0, np.pi, 5)))

print("\nCeiling Values:", np.ceil(np.array([1.2, 3.7])))
print("\nFloor Values:", np.floor(np.array([1.9, 3.1])))

print("\nRounded Values:", np.round(np.array([1.56, 3.44]), 1))

Square Root: [1. 2. 3. 4.]

Square: [  1  16  81 256]

Absolute Values: [1 2 3]

Exponential: [1.         2.71828183 7.3890561 ]

Natural Logarithm: [0.         1.38629436 2.19722458 2.77258872]

Base-2 Logarithm: [0.       2.       3.169925 4.      ]

Base-10 Logarithm: [0.         0.60205999 0.95424251 1.20411998]

Sine Values: [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]

Ceiling Values: [2. 4.]

Floor Values: [1. 3.]

Rounded Values: [1.6 3.4]


## 5.3 Aggregate Functions

In [89]:
m = np.array([[1, 2, 3],[4, 5, 6]])
print("Original Matrix:\n", m)
print("\nSum:", np.sum(m))
print("Sum (axis=0):", np.sum(m, axis=0))
print("Sum (axis=1):", np.sum(m, axis=1))

print("\nMean:", np.mean(m))
print("Standard Deviation:",np.std(m))
print("Variance:", np.var(m))

print("\nMinimum Value:", np.min(m))
print("Maximum Value:", np.max(m))

print("Index of Minimum Value:", np.argmin(m))
print("Index of Maximum Value:", np.argmax(m))

print("\nCumulative Sum (axis=1):", np.cumsum(m, axis=1))

print("Product (axis=0):", np.prod(m, axis=0))

Original Matrix:
 [[1 2 3]
 [4 5 6]]

Sum: 21
Sum (axis=0): [5 7 9]
Sum (axis=1): [ 6 15]

Mean: 3.5
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665

Minimum Value: 1
Maximum Value: 6
Index of Minimum Value: 0
Index of Maximum Value: 5

Cumulative Sum (axis=1): [[ 1  3  6]
 [ 4  9 15]]
Product (axis=0): [ 4 10 18]


## 5.4 Broadcasting Basics

In [93]:
import numpy as np 
a = np.array([1, 2, 3, 4])
print("Array after adding 100:", a + 100)

m = np.array([[1, 2, 3],[4, 5, 6]]) 
print("\nOriginal Matrix:")
print(m)

row = np.array([10, 20, 30]) 
print("\nMatrix + Row vector:")
print(m + row)

col = np.array([[100], [200]])
print("\nMatrix + Column vector:")
print(m + col)

Array after adding 100: [101 102 103 104]

Original Matrix:
[[1 2 3]
 [4 5 6]]

Matrix + Row vector:
[[11 22 33]
 [14 25 36]]

Matrix + Column vector:
[[101 102 103]
 [204 205 206]]


## 5.5 Tasks — Operations


Task 5.5.1: Create two 3×3 random arrays A and B. Compute element-wise product, division, and A raised to power B.

Task 5.5.2: Normalise an array of 10 random values (make mean=0, std=1). Verify with .mean() and .std().

Task 5.5.3: Given a 4×5 matrix of random integers 1–50, find: overall sum, row-wise max, columnwise mean, and the index 
of the global minimum.

Task 5.5.4: Use broadcasting to create the multiplication table for numbers 1–9 as a 9×9 matrix. No loops allowed.

Task 5.5.5: Apply np.sin and np.cos to 100 evenly spaced angles from 0 to 2π. Verify that sin²(x) + cos²(x) ≈ 1 for all values.

In [94]:
print("Task 5.5.1\n")

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("A:")
print(A)

print("\nB:")
print(B)

print("\nElement-wise Product:")
print(A * B)

print("\nElement-wise Division:")
print(A / B)

print("\nA Raised to Power B:")
print(A ** B)

Task 5.5.1

A:
[[3 4 4]
 [4 1 6]
 [7 8 2]]

B:
[[5 6 5]
 [5 3 3]
 [5 8 5]]

Element-wise Product:
[[15 24 20]
 [20  3 18]
 [35 64 10]]

Element-wise Division:
[[0.6        0.66666667 0.8       ]
 [0.8        0.33333333 2.        ]
 [1.4        1.         0.4       ]]

A Raised to Power B:
[[     243     4096     1024]
 [    1024        1      216]
 [   16807 16777216       32]]


In [95]:
print("Task 5.5.2\n")

arr = np.random.rand(10)

normalized = (arr - arr.mean()) / arr.std()

print("Original Array:")
print(arr)

print("\nNormalized Array:")
print(normalized)

print("\nMean:")
print(normalized.mean())

print("\nStandard Deviation:")
print(normalized.std())

Task 5.5.2

Original Array:
[0.39616482 0.53062476 0.57124998 0.21279965 0.02771901 0.90562674
 0.8875509  0.20909362 0.22015022 0.57074122]

Normalized Array:
[-0.20371743  0.27677974  0.42195534 -0.85897906 -1.52037098  1.616862
  1.55226737 -0.8722227  -0.83271153  0.42013726]

Mean:
-1.3322676295501878e-16

Standard Deviation:
1.0


In [96]:
print("Task 5.5.3\n")

m = np.random.randint(1, 51, (4, 5))

print("Matrix:")
print(m)

print("\nOverall Sum:")
print(np.sum(m))

print("\nRow-wise Maximum:")
print(np.max(m, axis=1))

print("\nColumn-wise Mean:")
print(np.mean(m, axis=0))

print("\nIndex of Global Minimum:")
print(np.argmin(m))

Task 5.5.3

Matrix:
[[42 49 22  6  9]
 [28 41 49 45 26]
 [50  4  9 42 11]
 [36 20  1 16  1]]

Overall Sum:
507

Row-wise Maximum:
[49 49 50 36]

Column-wise Mean:
[39.   28.5  20.25 27.25 11.75]

Index of Global Minimum:
17


In [97]:
print("Task 5.5.4\n")
a = np.arange(1, 10)

table = a[:, np.newaxis] * a

print("Multiplication Table (1-9):")
print(table)

Task 5.5.4

Multiplication Table (1-9):
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [98]:
print("Task 5.5.5\n")
angles = np.linspace(0, 2 * np.pi, 100)

sin_values = np.sin(angles)
cos_values = np.cos(angles)

result = sin_values**2 + cos_values**2

print("sin²(x) + cos²(x):")
print(result)

print("\nAll Values Approximately Equal to 1:")
print(np.allclose(result, 1))

Task 5.5.5

sin²(x) + cos²(x):
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]

All Values Approximately Equal to 1:
True


## 6 Reshaping, Stacking & Splitting

### 6.1 Reshape

In [ ]:
import numpy as np
a = np.arange(24)
b = a.reshape(4, 6)
c = a.reshape(2, 3, 4)
d = a.reshape(8, -1)
flat_view = b.ravel()
flat_copy = b.flatten()
x = np.array([1, 2, 3])
print('x[:, np.newaxis] shape:', x[:, np.newaxis].shape)
print(x[:, np.newaxis])
print('x[np.newaxis, :] shape:', x[np.newaxis, :].shape)
print(x[np.newaxis, :])

### 6.2 Stacking & Splitting
concat/vstack/hstack/stack and splitting with `vsplit`/`hsplit`.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print('vstack:')
print(np.vstack([a, b]))
print('\nhstack:')
print(np.hstack([a, b]))
print('\nconcatenate axis=0:')
print(np.concatenate([a, b], axis=0))
print('\nstack axis=0 shape:')
print(np.stack([a, b], axis=0).shape)
x = np.arange(12).reshape(4, 3)
print('\nx:')
print(x)
print('\nvsplit into 2:')
print(np.vsplit(x, 2))
print('\nhsplit into 3:')
print(np.hsplit(x, 3))

### 6.3 Tasks — Reshape & Stack

Task 6.3.1: Create a 1D array of 30 elements and reshape it into (5, 6), (2, 3, 5), and (6, 5). Confirm all have 30 elements.

Task 6.3.2: Stack two 3×4 arrays vertically and horizontally. Print the shape of each result.

Task 6.3.3: Create a column vector from [10, 20, 30, 40] using `np.newaxis`. Add it to a 4×3 matrix using broadcasting.

In [108]:
print('Task 6.3.1\n')
arr = np.arange(30)
print("Original Array:", arr)
a1 = arr.reshape(5, 6)
print(a1)
a2 = arr.reshape(2, 3, 5)
print(a2)
a3 = arr.reshape(6, 5)
print(a3)

print('\nShapes:', a1.shape, a2.shape, a3.shape)
print('Sizes:', a1.size, a2.size, a3.size)
print('All sizes 30?', (a1.size == 30 and a2.size == 30 and a3.size == 30))


Task 6.3.1

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Shapes: (5, 6) (2, 3, 5) (6, 5)
Sizes: 30 30 30
All sizes 30? True


In [111]:
print('Task 6.3.2\n')
A = np.random.randint(1, 10, (3, 4))
print("A:\n", A)

B = np.random.randint(10, 20, (3, 4))
print("B:\n", B)
v = np.vstack([A, B])
print("vstack:\n", v)
h = np.hstack([A, B])
print("hstack:\n", h)
print('A shape:', A.shape, 'B shape:', B.shape)
print('vstack shape:', v.shape)
print('hstack shape:', h.shape)


Task 6.3.2

A:
 [[3 8 8 1]
 [1 8 4 3]
 [9 2 2 9]]
B:
 [[12 16 13 12]
 [17 12 12 15]
 [12 18 13 14]]
vstack:
 [[ 3  8  8  1]
 [ 1  8  4  3]
 [ 9  2  2  9]
 [12 16 13 12]
 [17 12 12 15]
 [12 18 13 14]]
hstack:
 [[ 3  8  8  1 12 16 13 12]
 [ 1  8  4  3 17 12 12 15]
 [ 9  2  2  9 12 18 13 14]]
A shape: (3, 4) B shape: (3, 4)
vstack shape: (6, 4)
hstack shape: (3, 8)


In [104]:
print('Task 6.3.3\n')
col = np.array([10, 20, 30, 40])[:, np.newaxis]  # (4,1)
m = np.arange(1, 13).reshape(4, 3)
print('Column vector:')
print(col)
print('\nMatrix:')
print(m)
print('\nBroadcasted sum (m + col):')
print(m + col)

Task 6.3.3

Column vector:
[[10]
 [20]
 [30]
 [40]]

Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Broadcasted sum (m + col):
[[11 12 13]
 [24 25 26]
 [37 38 39]
 [50 51 52]]
