## 1. Advanced Boolean & Fancy Indexing 
## 1.1 Compound Boolean Conditions 

In [2]:
import numpy as np

data = np.array([15, 42, -3, 87, -12, 55, 0, 33])

pos_small = data[(data > 0) & (data < 50)]
print("Positive values less than 50:", pos_small)

neg_or_big = data[(data < 0) | (data > 80)]
print("Negative values or values greater than 80:", neg_or_big)

not_zero = data[~(data == 0)]
print("Values not equal to zero:", not_zero)

print("Any values less than 0:", np.any(data < 0))
print("All values greater than 0:", np.all(data > 0))
print("All values greater than 0 (axis=0):", np.all(data > 0, axis=0))

idx = np.nonzero(data > 40)
print("Indices of values greater than 40:", idx)
print("Values greater than 40:", data[idx])

Positive values less than 50: [15 42 33]
Negative values or values greater than 80: [ -3  87 -12]
Values not equal to zero: [ 15  42  -3  87 -12  55  33]
Any values less than 0: True
All values greater than 0: False
All values greater than 0 (axis=0): False
Indices of values greater than 40: (array([1, 3, 5]),)
Values greater than 40: [42 87 55]


## 1.2 np.where — Vectorised if-else

In [3]:
scores = np.array([45, 82, 67, 55, 91, 38, 74])

clipped = np.where(scores >= 60, scores, 60)
print("Scores after replacing values below 60:", clipped)

labels = np.where(scores >= 80, 'Dist',
         np.where(scores >= 60, 'Merit', 'Pass'))
print("Performance labels:", labels)

bonus = np.where(scores >= 80, scores * 1.1, scores)
print("Scores after applying bonus:", bonus.astype(int))

conds = [scores >= 80, scores >= 60, scores >= 40]
vals = ['A', 'B', 'C']
grades = np.select(conds, vals, default='D')

print("Grades assigned using np.select():", grades)

Scores after replacing values below 60: [60 82 67 60 91 60 74]
Performance labels: ['Pass' 'Dist' 'Merit' 'Pass' 'Dist' 'Pass' 'Merit']
Scores after applying bonus: [ 45  90  67  55 100  38  74]
Grades assigned using np.select(): ['C' 'A' 'B' 'C' 'A' 'D' 'B']


## 1.3 Fancy Indexing & np.ix_ 

In [4]:
m = np.arange(25).reshape(5, 5)

print("Selected rows (0, 2, 4):")
print(m[[0, 2, 4], :])

r = [0, 1, 2]
c = [4, 3, 2]
print("Elements at specified (row, column) pairs:")
print(m[r, c])

rows = [0, 2]
cols = [1, 3]
sub = m[np.ix_(rows, cols)]

print("Sub-matrix using np.ix_():")
print(sub)

print("Matrix after reversing rows:")
print(m[::-1, :])

print("Matrix after reversing columns:")
print(m[:, ::-1])

Selected rows (0, 2, 4):
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
Elements at specified (row, column) pairs:
[ 4  8 12]
Sub-matrix using np.ix_():
[[ 1  3]
 [11 13]]
Matrix after reversing rows:
[[20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
Matrix after reversing columns:
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]


## 1.4 Tasks — Advanced Indexing

Task 1.4.1: Given a 6×6 matrix of random integers 1–100, extract all elements that are divisible by both 3 and 5. 

Task 1.4.2: Use np.where to replace all values below the mean of an array with 0 and above with 1 (binarise). 

Task 1.4.3: Use np.ix_ to extract a 3×3 sub-matrix from rows [1,3,4] and columns [0,2,4] of a 5×5 array. 

Task 1.4.4: Sort a 4×4 random matrix row-wise and column-wise separately (without loops). 

Task 1.4.5: Use np.select to classify 15 random scores into: 'A'(≥85), 'B'(≥70), 'C'(≥55), 'D'(≥40), 'F'(below 40).

In [ ]:
print("Task 1.4.1")

matrix = np.random.randint(1, 101, size=(6, 6))

print("Original 6×6 matrix:")
print(matrix)

result = matrix[(matrix % 3 == 0) & (matrix % 5 == 0)]

print("Elements divisible by both 3 and 5:")
print(result)

Task 1.4.1
Original 6×6 matrix:
[[ 35   9  62  54  31  38]
 [ 88  36  97  74  79  56]
 [ 78  37  64  41  93   5]
 [ 34  56   1  42 100  56]
 [ 84  69  73  25   3  69]
 [ 94   8  89  96  32 100]]
Elements divisible by both 3 and 5:
[]


In [6]:
print("Task 1.4.2")

arr = np.random.randint(1, 101, size=10)

print("Original array:")
print(arr)

mean_value = np.mean(arr)

print("Mean of the array:")
print(mean_value)

binary = np.where(arr < mean_value, 0, 1)

print("Binarised array:")
print(binary)

Task 1.4.2
Original array:
[32 62 51 60 98 64 48 93 45 90]
Mean of the array:
64.3
Binarised array:
[0 0 0 0 1 0 0 1 0 1]


In [7]:
print("Task 1.4.3")

arr = np.arange(25).reshape(5, 5)

print("Original 5×5 array:")
print(arr)

rows = [1, 3, 4]
cols = [0, 2, 4]

sub_matrix = arr[np.ix_(rows, cols)]

print("Extracted 3×3 sub-matrix:")
print(sub_matrix)

Task 1.4.3
Original 5×5 array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Extracted 3×3 sub-matrix:
[[ 5  7  9]
 [15 17 19]
 [20 22 24]]


In [8]:
print("Task 1.4.4")

matrix = np.random.randint(1, 101, size=(4, 4))

print("Original 4×4 matrix:")
print(matrix)

row_sorted = np.sort(matrix, axis=1)

print("Row-wise sorted matrix:")
print(row_sorted)

column_sorted = np.sort(matrix, axis=0)

print("Column-wise sorted matrix:")
print(column_sorted)

Task 1.4.4
Original 4×4 matrix:
[[49 25 55 95]
 [57 51 91 19]
 [54 45 96 42]
 [11 75 29 47]]
Row-wise sorted matrix:
[[25 49 55 95]
 [19 51 57 91]
 [42 45 54 96]
 [11 29 47 75]]
Column-wise sorted matrix:
[[11 25 29 19]
 [49 45 55 42]
 [54 51 91 47]
 [57 75 96 95]]


In [9]:
print("Task 1.4.5")

scores = np.random.randint(0, 101, size=15)

print("Random scores:")
print(scores)

conditions = [
    scores >= 85,
    scores >= 70,
    scores >= 55,
    scores >= 40
]

choices = ['A', 'B', 'C', 'D']

grades = np.select(conditions, choices, default='F')

print("Assigned grades:")
print(grades)

Task 1.4.5
Random scores:
[100 100  28  28  84  25  10  86  57  48  25  98  22  48  64]
Assigned grades:
['A' 'A' 'F' 'F' 'B' 'F' 'F' 'A' 'C' 'D' 'F' 'A' 'F' 'D' 'C']


## 2. Broadcasting — Deep Dive 

Broadcasting allows NumPy to perform operations on arrays of different shapes without copying data, 
following three rules. 

## 2.1 Broadcasting Rules 

- Rule 1: If arrays have different ndim, the shape of the smaller is padded with 1s on the LEFT. 
- Rule 2: Arrays with size 1 along any dimension are stretched to match the other. 
- Rule 3: If sizes differ and neither is 1 → ValueError.

In [10]:
col = np.array([[0], [10], [20]])
row = np.array([1, 2, 3, 4])

print("Result of broadcasting (column + row):")
print(col + row)

data = np.random.randint(1, 100, (4, 5)).astype(float)

print("Original data:")
print(data)

row_means = data.mean(axis=1, keepdims=True)
centred = data - row_means

print("Row means:")
print(row_means)

print("Data after centering:")
print(centred)

print("Mean of each row after centering:")
print(centred.mean(axis=1))

a = np.array([1, 2, 3])[:, np.newaxis]
b = np.array([10, 20, 30, 40])

print("Outer product using broadcasting:")
print(a * b)

Result of broadcasting (column + row):
[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]
Original data:
[[50.  1. 41. 79. 23.]
 [89.  4.  6. 77. 58.]
 [79. 71. 17. 34. 39.]
 [71. 19. 22. 77. 43.]]
Row means:
[[38.8]
 [46.8]
 [48. ]
 [46.4]]
Data after centering:
[[ 11.2 -37.8   2.2  40.2 -15.8]
 [ 42.2 -42.8 -40.8  30.2  11.2]
 [ 31.   23.  -31.  -14.   -9. ]
 [ 24.6 -27.4 -24.4  30.6  -3.4]]
Mean of each row after centering:
[2.84217094e-15 2.84217094e-15 0.00000000e+00 1.42108547e-15]
Outer product using broadcasting:
[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]]


## 2.2 Tasks — Broadcasting

Task 2.2.1: Without loops, add [1, 2, 3, 4] to every row of a (5,4) matrix and subtract [10,20,30,40,50] from every column. 

Task 2.2.2: Normalise each column of a 6×4 random matrix to have mean=0 and std=1 using broadcasting. 

Task 2.2.3: Build a distance matrix: given 5 points on a number line, create a 5×5 matrix where entry 
[i,j] = |points[i] - points[j]|. Use broadcasting, no loops.

In [11]:
print("Task 2.2.1")

matrix = np.random.randint(1, 100, size=(5, 4))

print("Original 5×4 matrix:")
print(matrix)

row_values = np.array([1, 2, 3, 4])
result = matrix + row_values

column_values = np.array([10, 20, 30, 40, 50]).reshape(5, 1)
result = result - column_values

print("Matrix after adding to rows and subtracting from columns:")
print(result)

Task 2.2.1
Original 5×4 matrix:
[[66 88 50 72]
 [24 36 29 83]
 [12 67 68 24]
 [66 71 23  6]
 [82 77 91 97]]
Matrix after adding to rows and subtracting from columns:
[[ 57  80  43  66]
 [  5  18  12  67]
 [-17  39  41  -2]
 [ 27  33 -14 -30]
 [ 33  29  44  51]]


In [12]:
print("Task 2.2.2")

matrix = np.random.randint(1, 100, size=(6, 4)).astype(float)

print("Original 6×4 matrix:")
print(matrix)

column_means = matrix.mean(axis=0, keepdims=True)
column_stds = matrix.std(axis=0, keepdims=True)

normalized = (matrix - column_means) / column_stds

print("Normalized matrix:")
print(normalized)

print("Mean of each column:")
print(normalized.mean(axis=0))

print("Standard deviation of each column:")
print(normalized.std(axis=0))

Task 2.2.2
Original 6×4 matrix:
[[52. 72. 51. 99.]
 [21. 75. 40. 36.]
 [51. 22. 45.  5.]
 [ 5. 51. 25. 17.]
 [96. 11.  6. 30.]
 [90. 11. 17. 61.]]
Normalized matrix:
[[-0.01513358  1.17266079  1.27193793  1.85774657]
 [-0.95341528  1.28375497  0.58384036 -0.17181471]
 [-0.04540073 -0.67890888  0.89661198 -1.17048772]
 [-1.4376897   0.39500153 -0.3544745  -0.78390462]
 [ 1.31662109 -1.0862542  -1.54300666 -0.36510626]
 [ 1.13501818 -1.0862542  -0.8549091   0.63356675]]
Mean of each column:
[ 0.00000000e+00 -7.40148683e-17 -9.25185854e-17 -5.55111512e-17]
Standard deviation of each column:
[1. 1. 1. 1.]


In [13]:
print("Task 2.2.3")

points = np.random.randint(1, 50, size=5)

print("Points on number line:")
print(points)

distance_matrix = np.abs(points[:, np.newaxis] - points)

print("Distance matrix:")
print(distance_matrix)

Task 2.2.3
Points on number line:
[32 40 38 36 11]
Distance matrix:
[[ 0  8  6  4 21]
 [ 8  0  2  4 29]
 [ 6  2  0  2 27]
 [ 4  4  2  0 25]
 [21 29 27 25  0]]


## 3. Linear Algebra with np.linalg 

## 3.1 Matrix Multiplication 

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix multiplication using np.dot():")
print(np.dot(A, B))

print("Matrix multiplication using @ operator:")
print(A @ B)

print("Matrix multiplication using np.matmul():")
print(np.matmul(A, B))

print("Element-wise multiplication:")
print(A * B)

print("Matrix multiplication:")
print(A @ B)

Matrix multiplication using np.dot():
[[19 22]
 [43 50]]
Matrix multiplication using @ operator:
[[19 22]
 [43 50]]
Matrix multiplication using np.matmul():
[[19 22]
 [43 50]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]


## 3.2 linalg Functions 

In [15]:
A = np.array([[2., 1.], [1., 3.]])

Ai = np.linalg.inv(A)

print("Inverse of matrix A:")
print(Ai)

print("A multiplied by its inverse (Identity matrix):")
print(A @ Ai)

print("Determinant of A:")
print(np.linalg.det(A))

vals, vecs = np.linalg.eig(A)

print("Eigenvalues of A:")
print(vals)

print("Eigenvectors of A:")
print(vecs)

b = np.array([8., 13.])

x = np.linalg.solve(A, b)

print("Solution vector x:")
print(x)

print("Verification (A @ x):")
print(A @ x)

v = np.array([3., 4.])

print("L2 norm of vector v:")
print(np.linalg.norm(v))

print("Frobenius norm of matrix A:")
print(np.linalg.norm(A, 'fro'))

Inverse of matrix A:
[[ 0.6 -0.2]
 [-0.2  0.4]]
A multiplied by its inverse (Identity matrix):
[[ 1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00]]
Determinant of A:
5.000000000000001
Eigenvalues of A:
[1.38196601 3.61803399]
Eigenvectors of A:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
Solution vector x:
[2.2 3.6]
Verification (A @ x):
[ 8. 13.]
L2 norm of vector v:
5.0
Frobenius norm of matrix A:
3.872983346207417


## 3.3 Tasks — Linear Algebra 

Task 3.3.1: Create a random 3×3 matrix A. Verify A @ inv(A) ≈ identity using np.allclose. 

Task 3.3.2: Solve the system: 2x+y=5, x+3y=10 using np.linalg.solve. Verify your answer. 

Task 3.3.3: Generate a symmetric matrix S = A.T @ A. Compute its eigenvalues and verify they are all non-negative. 

Task 3.3.4: Compute the dot product of two random unit vectors (normalise with np.linalg.norm first). Interpret the result.

In [16]:
print("Task 3.3.1")

A = np.random.randint(1, 10, size=(3, 3)).astype(float)

print("Matrix A:")
print(A)

A_inv = np.linalg.inv(A)

identity_check = A @ A_inv

print("A @ inv(A):")
print(identity_check)

print("Is A @ inv(A) approximately equal to Identity matrix?")
print(np.allclose(identity_check, np.eye(3)))

Task 3.3.1
Matrix A:
[[6. 1. 8.]
 [7. 5. 6.]
 [7. 6. 5.]]
A @ inv(A):
[[ 1.00000000e+00  0.00000000e+00  7.10542736e-15]
 [-8.88178420e-16  1.00000000e+00 -7.10542736e-15]
 [ 4.44089210e-16  3.55271368e-15  1.00000000e+00]]
Is A @ inv(A) approximately equal to Identity matrix?
True


In [17]:
print("Task 3.3.2")

A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 10])

solution = np.linalg.solve(A, b)

print("Solution [x, y]:")
print(solution)

print("Verification (A @ solution):")
print(A @ solution)

Task 3.3.2
Solution [x, y]:
[1. 3.]
Verification (A @ solution):
[ 5. 10.]


In [18]:
print("Task 3.3.3")

A = np.random.randint(1, 10, size=(3, 3))

S = A.T @ A

print("Symmetric matrix S = A.T @ A:")
print(S)

eigenvalues, eigenvectors = np.linalg.eig(S)

print("Eigenvalues of S:")
print(eigenvalues)

print("Are all eigenvalues non-negative?")
print(np.all(eigenvalues >= 0))

Task 3.3.3
Symmetric matrix S = A.T @ A:
[[146  98  63]
 [ 98  77  53]
 [ 63  53  38]]
Eigenvalues of S:
[247.54756333  13.15738703   0.29504964]
Are all eigenvalues non-negative?
True


In [19]:
print("Task 3.3.4")

v1 = np.random.rand(3)
v2 = np.random.rand(3)

v1 = v1 / np.linalg.norm(v1)
v2 = v2 / np.linalg.norm(v2)

dot_product = np.dot(v1, v2)

print("First unit vector:")
print(v1)

print("Second unit vector:")
print(v2)

print("Dot product of the two unit vectors:")
print(dot_product)

print("Interpretation:")
print("A value close to 1 means vectors are similar, close to 0 means nearly perpendicular, and close to -1 means opposite directions.")

Task 3.3.4
First unit vector:
[0.21282343 0.83001888 0.51553355]
Second unit vector:
[0.75508776 0.47585437 0.45100454]
Dot product of the two unit vectors:
0.7881764536410809
Interpretation:
A value close to 1 means vectors are similar, close to 0 means nearly perpendicular, and close to -1 means opposite directions.


## 4. Sorting, Searching & Set Operations 
## 4.1 Sorting

In [20]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

print("Sorted copy of array:")
print(np.sort(arr))

arr.sort()

print("Array after in-place sorting:")
print(arr)

print("Indices that would sort the array:")
print(np.argsort(arr))

m = np.random.randint(1, 20, (3, 4))

print("Original matrix:")
print(m)

print("Row-wise sorted matrix:")
print(np.sort(m, axis=1))

print("Column-wise sorted matrix:")
print(np.sort(m, axis=0))

k = 3
top_idx = np.argsort(arr)[-k:][::-1]

print("Largest 3 elements:")
print(arr[top_idx])

Sorted copy of array:
[1 1 2 3 4 5 5 6 9]
Array after in-place sorting:
[1 1 2 3 4 5 5 6 9]
Indices that would sort the array:
[0 1 2 3 4 5 6 7 8]
Original matrix:
[[ 5 10  6  8]
 [14 12  7 17]
 [ 5  6 14  6]]
Row-wise sorted matrix:
[[ 5  6  8 10]
 [ 7 12 14 17]
 [ 5  6  6 14]]
Column-wise sorted matrix:
[[ 5  6  6  6]
 [ 5 10  7  8]
 [14 12 14 17]]
Largest 3 elements:
[9 6 5]


## 4.2 Searching & Set Ops

In [21]:
arr = np.array([1, 1, 2, 3, 4, 4, 5])

vals, counts = np.unique(arr, return_counts=True)

print("Unique values:")
print(vals)

print("Count of each unique value:")
print(counts)

print("Index where 3 should be inserted:")
print(np.searchsorted(arr, 3))

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

print("Common elements:")
print(np.intersect1d(a, b))

print("Union of arrays:")
print(np.union1d(a, b))

print("Elements present only in A:")
print(np.setdiff1d(a, b))

print("Membership of elements of A in B:")
print(np.in1d(a, b))

Unique values:
[1 2 3 4 5]
Count of each unique value:
[2 1 1 2 1]
Index where 3 should be inserted:
3
Common elements:
[3 4 5]
Union of arrays:
[1 2 3 4 5 6 7]
Elements present only in A:
[1 2]
Membership of elements of A in B:
[False False  True  True  True]


C:\Users\prince patel\AppData\Local\Temp\ipykernel_22204\3574943687.py:27: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a, b))


## 4.3 Tasks — Sorting & Searching 

Task 4.3.1: Given a 1D array of 20 random integers, find the indices of the 5 smallest and 5 largest values without fully sorting. 

Task 4.3.2: Sort a 5×5 matrix so each row is sorted ascending and each column is sorted ascending (hint: sort rows first, then columns). 

Task 4.3.3: From two random integer arrays of size 15 (range 1–20), find common elements, elements only in A, and elements only in B. 

In [22]:
print("Task 4.3.1")

arr = np.random.randint(1, 100, size=20)

print("Original array:")
print(arr)

smallest_idx = np.argpartition(arr, 5)[:5]
largest_idx = np.argpartition(arr, -5)[-5:]

print("Indices of 5 smallest values:")
print(smallest_idx)

print("5 smallest values:")
print(arr[smallest_idx])

print("Indices of 5 largest values:")
print(largest_idx)

print("5 largest values:")
print(arr[largest_idx])

Task 4.3.1
Original array:
[89 60 79 19 92 10 95 33 63 31 48 87 23 60 48 57 51 85 39 78]
Indices of 5 smallest values:
[ 5  3 12  9  7]
5 smallest values:
[10 19 23 31 33]
Indices of 5 largest values:
[17 11  0  4  6]
5 largest values:
[85 87 89 92 95]


In [23]:
print("Task 4.3.2")

matrix = np.random.randint(1, 100, size=(5, 5))

print("Original matrix:")
print(matrix)

row_sorted = np.sort(matrix, axis=1)
final_matrix = np.sort(row_sorted, axis=0)

print("Matrix with rows and columns sorted ascending:")
print(final_matrix)

Task 4.3.2
Original matrix:
[[63 54 60 84 18]
 [ 7 27 51 18 59]
 [36 81 53 35 30]
 [89  7 13 49 99]
 [16 49 94 75  2]]
Matrix with rows and columns sorted ascending:
[[ 2 13 27 51 59]
 [ 7 16 36 53 81]
 [ 7 18 49 63 84]
 [18 35 49 75 94]
 [30 54 60 89 99]]


In [24]:
print("Task 4.3.3")

A = np.random.randint(1, 21, size=15)
B = np.random.randint(1, 21, size=15)

print("Array A:")
print(A)

print("Array B:")
print(B)

print("Common elements:")
print(np.intersect1d(A, B))

print("Elements only in A:")
print(np.setdiff1d(A, B))

print("Elements only in B:")
print(np.setdiff1d(B, A))

Task 4.3.3
Array A:
[11  3  2  6  5 19  8 20 19  2  3 10 13  6  2]
Array B:
[ 6 16  1 20  7 15 12 10 20  5 16  7  6 18 19]
Common elements:
[ 5  6 10 19 20]
Elements only in A:
[ 2  3  8 11 13]
Elements only in B:
[ 1  7 12 15 16 18]


## 5. Working with Real Data 
## 5.1 Loading & Saving

In [31]:
arr = np.arange(100).reshape(10, 10)

np.save("data.npy", arr)
loaded = np.load("data.npy")

print("Loaded array from .npy file:")
print(loaded)

np.savez("multi.npz", arr1=arr, arr2=arr * 2)

f = np.load("multi.npz")

print("Shape of arr1:")
print(f["arr1"].shape)

print("Shape of arr2:")
print(f["arr2"].shape)

np.savetxt("out.csv", arr, delimiter=",", fmt="%d")

back = np.loadtxt("out.csv", delimiter=",", dtype=int)

print("Array loaded from CSV:")
print(back)

data = np.genfromtxt(
    "messy.csv",
    delimiter=",",
    filling_values=0,
    skip_header=1
)

print("Data loaded using genfromtxt:")
print(data)

Loaded array from .npy file:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
Shape of arr1:
(10, 10)
Shape of arr2:
(10, 10)
Array loaded from CSV:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
Data loaded using genfromtxt:
[[ 1. 85. 92. 78.]
 [ 2. 76.  0. 88.]
 [ 3. 90. 81.  0.]
 [ 4.  0. 75. 69.]
 [ 5. 68. 72. 80.]
 [ 6. 95.  0. 91.]
 [ 7. 82. 79. 77.]
 [ 8.  0. 85.  0.]]


## 5.2 Column Operations on Loaded Data 

In [26]:
data = np.column_stack([
    np.arange(1, 11),
    np.random.randint(40, 100, (10, 3))
]).astype(float)

print("Student dataset:")
print(data)

ids = data[:, 0]
math = data[:, 1]
science = data[:, 2]
english = data[:, 3]

avg = data[:, 1:].mean(axis=1)
total = data[:, 1:].sum(axis=1)
rank = total.argsort()[::-1].argsort() + 1

best_sub = np.argmax(data[:, 1:].mean(axis=0))

print("Average marks of each student:")
print(avg)

print("Total marks of each student:")
print(total)

print("Ranks of students:")
print(rank)

print("Best subject index:")
print(best_sub)

Student dataset:
[[ 1. 59. 71. 50.]
 [ 2. 99. 49. 96.]
 [ 3. 43. 55. 40.]
 [ 4. 48. 83. 55.]
 [ 5. 92. 56. 42.]
 [ 6. 69. 68. 59.]
 [ 7. 64. 88. 74.]
 [ 8. 79. 54. 75.]
 [ 9. 63. 92. 95.]
 [10. 41. 66. 96.]]
Average marks of each student:
[60.         81.33333333 46.         62.         63.33333333 65.33333333
 75.33333333 69.33333333 83.33333333 67.66666667]
Total marks of each student:
[180. 244. 138. 186. 190. 196. 226. 208. 250. 203.]
Ranks of students:
[ 9  2 10  8  7  6  3  4  1  5]
Best subject index:
1


## 5.3 Tasks — File I/O & Data 

Task 5.3.1: Create a 20×5 random float array, save it as both .npy and .csv, reload both, and confirm they are equal using np.allclose. 

Task 5.3.2: Simulate a dataset of 50 students with 4 subject marks. Save to CSV. Reload and compute: class topper, subject-wise averages, and students scoring below 50 in any subject. 

In [32]:
print("Task 5.3.1")

arr = np.random.rand(20, 5)

print("Original array:")
print(arr)

np.save("array.npy", arr)
np.savetxt("array.csv", arr, delimiter=",")

npy_data = np.load("array.npy")
csv_data = np.loadtxt("array.csv", delimiter=",")

print("Array loaded from .npy file:")
print(npy_data)

print("Array loaded from .csv file:")
print(csv_data)

print("Are both arrays equal?")
print(np.allclose(npy_data, csv_data))

Task 5.3.1
Original array:
[[0.46433263 0.91309676 0.22399613 0.73412603 0.11537813]
 [0.17674995 0.96482257 0.80395311 0.34292175 0.79271776]
 [0.2500351  0.08313622 0.02932924 0.54437935 0.90433154]
 [0.40789767 0.55912357 0.1821677  0.77854732 0.17291227]
 [0.57982377 0.35280948 0.82976207 0.07205101 0.87713379]
 [0.21113083 0.74301167 0.16287493 0.28724256 0.12190165]
 [0.50574259 0.39265703 0.8129899  0.02748113 0.23863191]
 [0.46931255 0.23129297 0.19161114 0.79042988 0.57331562]
 [0.57478748 0.96902971 0.71702898 0.23558417 0.63858316]
 [0.78619896 0.42467793 0.8919086  0.33520866 0.74765409]
 [0.32953858 0.47972182 0.02226391 0.10184344 0.78654759]
 [0.51238388 0.41452857 0.12465053 0.62314448 0.89076863]
 [0.86290414 0.28269516 0.08775869 0.99438808 0.67703724]
 [0.55313098 0.33763559 0.85345852 0.830404   0.10011807]
 [0.71303533 0.12796893 0.38501305 0.46777653 0.20237641]
 [0.50280694 0.86044912 0.80300187 0.4924166  0.06421474]
 [0.30729342 0.76170415 0.66189094 0.18697923

In [33]:
print("Task 5.3.2")

marks = np.random.randint(30, 101, size=(50, 4))

np.savetxt("students.csv", marks, delimiter=",", fmt="%d")

data = np.loadtxt("students.csv", delimiter=",")

print("Student marks dataset:")
print(data)

totals = data.sum(axis=1)
topper_index = np.argmax(totals)

subject_averages = data.mean(axis=0)

below_50 = data[np.any(data < 50, axis=1)]

print("Class topper index:")
print(topper_index)

print("Marks of class topper:")
print(data[topper_index])

print("Subject-wise averages:")
print(subject_averages)

print("Students scoring below 50 in at least one subject:")
print(below_50)

Task 5.3.2
Student marks dataset:
[[ 59.  44.  85.  34.]
 [ 81.  52.  58.  93.]
 [ 80.  48.  58.  41.]
 [ 60.  41.  35.  98.]
 [ 68.  75.  51.  81.]
 [ 94.  32.  41.  52.]
 [ 82.  39.  56.  87.]
 [ 62.  99.  33.  55.]
 [ 85.  64.  91.  52.]
 [ 78.  63.  37.  68.]
 [ 99.  88.  88.  65.]
 [ 76.  91.  30.  96.]
 [ 84.  33.  62.  68.]
 [ 77.  70.  39.  95.]
 [ 54.  57.  50.  61.]
 [ 30.  80.  60.  53.]
 [ 47.  52.  42.  75.]
 [ 64.  48.  94.  37.]
 [ 68.  48.  99.  94.]
 [ 79.  67.  87.  86.]
 [ 41.  56.  41.  78.]
 [ 36.  45.  64.  95.]
 [ 76.  44.  71.  72.]
 [ 59.  65.  74.  51.]
 [ 46.  58.  59.  95.]
 [ 36.  68.  85.  45.]
 [ 57.  90.  52.  39.]
 [ 42.  80.  54.  48.]
 [ 94.  82.  75.  99.]
 [ 65.  97.  33.  86.]
 [ 85.  53.  75.  42.]
 [ 60.  52.  83.  79.]
 [ 42.  80.  61.  89.]
 [ 68.  46.  67.  73.]
 [ 61.  79.  75.  81.]
 [ 99.  71.  62.  81.]
 [ 49.  95.  88.  91.]
 [ 96.  84.  98.  57.]
 [ 60.  79.  44.  37.]
 [ 66.  74.  66.  30.]
 [ 92.  40.  94.  77.]
 [ 97.  72.  67.  79.]


## 6. Performance & Vectorisation 
## 6.1 Vectorisation Patterns

In [34]:
import time

n = 3_000_000

a = np.random.rand(n)
b = np.random.rand(n)

start = time.perf_counter()
c = [a[i] + b[i] for i in range(n)]
print(f"Loop execution time: {time.perf_counter() - start:.3f} seconds")

start = time.perf_counter()
c = a + b
print(f"NumPy execution time: {time.perf_counter() - start:.4f} seconds")

a += b

np.add(a, b, out=a)

result = np.empty(n)

np.multiply(a, b, out=result)

print("Multiplication result stored using pre-allocation.")

Loop execution time: 0.736 seconds
NumPy execution time: 0.0423 seconds
Multiplication result stored using pre-allocation.


## 6.2 einsum & Advanced

In [35]:
A = np.random.rand(100, 200)
B = np.random.rand(200, 150)

C = np.einsum('ij,jk->ik', A, B)

print("Shape of result matrix C:")
print(C.shape)

M = np.random.rand(5, 5)

print("Trace of matrix M using einsum:")
print(np.einsum('ii->', M))

a = np.random.rand(10, 4)
b = np.random.rand(10, 4)

print("Row-wise dot products:")
print(np.einsum('ij,ij->i', a, b))

Shape of result matrix C:
(100, 150)
Trace of matrix M using einsum:
1.8545476455177465
Row-wise dot products:
[0.35759072 0.46327524 0.83969928 2.47866012 0.43449073 0.40986183
 1.52247034 0.86227746 0.28886216 1.49188609]


## 6.3 Tasks — Performance 

Task 6.3.1: Rewrite the following loop using vectorisation: result = []; for i in range(len(x)): result.append(x[i]**2 + 2*x[i] + 1). Benchmark both. 

Task 6.3.2: Use np.einsum to compute the outer product of two vectors and verify it matches np.outer. 

Task 6.3.3: Generate a float32 and float64 array of 1M elements. Compare memory usage and 
computation speed for squaring each.

In [36]:
print("Task 6.3.1")

x = np.random.rand(1_000_000)

start = time.perf_counter()

result_loop = []
for i in range(len(x)):
    result_loop.append(x[i]**2 + 2*x[i] + 1)

loop_time = time.perf_counter() - start

start = time.perf_counter()

result_vectorized = x**2 + 2*x + 1

vector_time = time.perf_counter() - start

print(f"Loop execution time: {loop_time:.4f} seconds")
print(f"Vectorized execution time: {vector_time:.4f} seconds")

Task 6.3.1
Loop execution time: 0.5676 seconds
Vectorized execution time: 0.0211 seconds


In [37]:
print("Task 6.3.2")

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

outer_einsum = np.einsum('i,j->ij', a, b)
outer_np = np.outer(a, b)

print("Outer product using einsum:")
print(outer_einsum)

print("Outer product using np.outer:")
print(outer_np)

print("Are both results equal?")
print(np.array_equal(outer_einsum, outer_np))

Task 6.3.2
Outer product using einsum:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Outer product using np.outer:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Are both results equal?
True


In [38]:
print("Task 6.3.3")

arr32 = np.random.rand(1_000_000).astype(np.float32)
arr64 = np.random.rand(1_000_000).astype(np.float64)

print("Memory used by float32 array:")
print(arr32.nbytes, "bytes")

print("Memory used by float64 array:")
print(arr64.nbytes, "bytes")

start = time.perf_counter()
square32 = arr32 ** 2
time32 = time.perf_counter() - start

start = time.perf_counter()
square64 = arr64 ** 2
time64 = time.perf_counter() - start

print(f"float32 squaring time: {time32:.6f} seconds")
print(f"float64 squaring time: {time64:.6f} seconds")

Task 6.3.3
Memory used by float32 array:
4000000 bytes
Memory used by float64 array:
8000000 bytes
float32 squaring time: 0.007956 seconds
float64 squaring time: 0.003206 seconds
